// <auto-generated />
namespace Barberville.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Barberville : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Barberville));
        
        string IMigrationMetadata.Id
        {
            get { return "202105092345445_Barberville"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
